%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{A schema for serializing R object types to JSON}

\documentclass{article}
\author{Jeroen Ooms}
\title{A schema for serializing R object types to JSON}

\usepackage{url}
\usepackage{fullpage}

\begin{document}

\maketitle

\abstract {
  This document lists some conventions on converting bewteen JSON and R objects.
}

\section*{Introduction}

blabla

\subsection*{\texttt{toJSON} versus \texttt{serializeJSON}}

blabla





\end{document}